final_project/urls.py
from django.contrib import admin
from django.urls import path, include

from users.models import Project, Status, CardClass, Tag, Request, RequestStatus

admin.site.register(CardClass)
admin.site.register(Status)
admin.site.register(Tag)
admin.site.register(Project)
admin.site.register(Request)
admin.site.register(RequestStatus)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('projects/', include("projects.urls", namespace='projects')),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("create/", views.create_view, name="create"),
    path("manage/", views.manage_view, name="manage"),
    path("manage/<int:project_id>/", views.manage_project_view, name="manage_project"),
    path("manage/<int:project_id>/modify_project", views.modify_project_view, name="modify_project"),
    path("request/<int:project_id>/", views.request_view, name="request"),
    path("myrequests/", views.myrequests_view, name="myrequests"),
    path("approve/<int:request_id>", views.approve_view, name="approve"),
    path("deny/<int:request_id>", views.deny_view, name="deny"),
    path("<int:request_id>/<int:modification_id>/modify/", views.request_modification_view, name="request_modification"),
    path("create_tag/", views.create_tag_view, name="create_tag"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
]

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class CardClass(models.Model):
    name = models.CharField(max_length=64)
    cardClass = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

class Status(models.Model):
    status = models.CharField(max_length=64)
    cardClass = models.ForeignKey('CardClass', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.status}"

class Tag(models.Model):
    tag = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.tag}"

class RequestStatus(models.Model):
    status = models.CharField(max_length=64)
    cardClass = models.ForeignKey('CardClass', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.status}"

#Will have to decide how to limit many to many
# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=64)
    manager = models.ForeignKey(User, on_delete=models.PROTECT, related_name='manager')
    status = models.ForeignKey('Status', on_delete=models.PROTECT,)
    contributors = models.ManyToManyField(User, related_name='contributor', blank=True,)
    description = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True,)

    def __str__(self):
        return f"{self.name} by {self.manager}"

class Request(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project')
    status = models.ForeignKey('RequestStatus', on_delete=models.PROTECT)
    note = models.TextField(max_length = 300)

    def __str__(self):
        return f"{self.sender}'s request for {self.project}: {self.status}"

users/forms.py
#Straight from https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import RegistrationForm


# Create your views here.
#Taken directly from source code 7
def index(request):
    return redirect('projects:home')

def login_view(request):
    next = request.META['HTTP_REFERER']
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        next = request.POST.get('next', '/')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(next)
        else:
            return render(request, "users/login.html", {"message": "Invalid credentials."})
    else:
        next = request.META['HTTP_REFERER']
        return render(request, "users/login.html", {'next': next})

def logout_view(request):
    logout(request)
    return redirect(reverse('users:index'))

def register_view(request):
#Shoutout for the tutorial to https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('users:index')
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {'form': form})

users/templates/users/base.html
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      {% load static %}
      <script src="{% static 'users/styles.css' %}"></script>

      {% block head %}
      {% endblock %}

      <title>ProDium</title>

    </head>
    <body class = "m-2">
      <div id = "body">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'projects:home' %}">Home<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <button class="nav-link" id = "login-link">Login<span class="sr-only">(current)</span></button>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:register' %}">Register<span class="sr-only">(current)</span></a>
              </li>
            </ul>
          </div>
        </nav>
        {% block body %}
        {% endblock %}
      </div>
      <div class = "login_form">
        <h2> Login Form </h2>
        <form action = "{% url 'users:login'%}">
          {% csrf_token %}
          <p>Username</p>
          <input type = "text" placeholder = "Username"></input>
          <p>Password</p>
          <input type = "password" placeholder = "Password"></input>
          <input type = "submit" value = "Sign In">
        </form>
      </div>
      <script>
        $( "#login-link" ).click(function() {
          $('#body').fadeTo( "slow" , .4);
          $('.login_form').fadeIn(1000);
          $('.login_form').show();
        });
      </script>
      <style>
      /* @@keyframes half_fade {
        to {
          opacity: .4,
        }
      } */
      /* .body {
        animation-name: half_fade;
        animation-duration: 1000;
        animation-play-state: paused;
      } */
      .login_form {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 400px;
        height: 500 px;
        padding: 60 px 40 px;
        background: #000000;
        display: none;
      }
      .login_form h2{
        margin: 0;
        padding: 0 0 20px;
        color: #fff;
        text-align: center;
        text-transform: uppercase;
      }
      .login_form p{
        margin: 0;
        padding: 0;
        font-weight: bold;
        color: #fff;
      }
      .login_form input{
        width: 100%;
        margin-bottom: 20px;
      }
      .login_form input[type="text"],
      .login_form input[type="password"]{
        border: none;
        border-bottom: 1 px;
        background: transparent;
        outline: none;
        height: 35px;
        color: #fff;
        font-size: 15 px;
      }
      .login_form input[type=submit]{

        height: 30px;
        color: #fff;
        font-size: 15px;
        background: red;
        cursor: pointer;
        border-radius: 25 px;
        border: none;
        outline: none;
        margin-top: 15%;
      }
      </style>
    </body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}

{% block body %}
<h1>Login</h1>
{% if message %}
    <div>
        {{ message }}
    </div>
{% endif %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input name="username" type="text"/>
    <input name="password" type="password"/>
    <input type='hidden' name='next' value="{{next}}">
    <input type="submit" value="Login"/>

</form>


<p> <a href= "{% url 'users:register' %}">Don't have an account? Register here</a></p>
{% endblock %}

users/templates/users/register.html
{% extends "users/base.html" %}

{% block body %}
<h1>Registration</h1>
{% if message %}
    <div>
        {{ message }}
    </div>
{% endif %}
<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {%for field in form %}
      <p>
        {{ field.label_tag}}<br>
        {{field}}
        {% if field.help_text %}
          <small style="color: grey"> {{field.help_text}} </small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Register</button>
</form>


<p> <a href= "{% url 'users:login' %}">Already have an account? Login here</a></p>
{% endblock %}