final_project/urls.py
from django.contrib import admin
from django.urls import path, include

from users.models import Project, Status, CardClass, Tag, Request, RequestStatus

admin.site.register(CardClass)
admin.site.register(Status)
admin.site.register(Tag)
admin.site.register(Project)
admin.site.register(Request)
admin.site.register(RequestStatus)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('projects/', include("projects.urls", namespace='projects')),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("create/", views.create_view, name="create"),
    path("manage/", views.manage_view, name="manage"),
    path("manage/<int:project_id>/", views.manage_project_view, name="manage_project"),
    path("manage/<int:project_id>/modify_project", views.modify_project_view, name="modify_project"),
    path("request/<int:project_id>/", views.request_view, name="request"),
    path("myrequests/", views.myrequests_view, name="myrequests"),
    path("approve/<int:request_id>", views.approve_view, name="approve"),
    path("deny/<int:request_id>", views.deny_view, name="deny"),
    path("<int:request_id>/<int:modification_id>/modify/", views.request_modification_view, name="request_modification"),
    path("create_tag/", views.create_tag_view, name="create_tag"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
]

projects/models.py
from django.db import models

# Create your models here.

projects/forms.py
from django.forms import ModelForm
from django.forms import forms
from users.models import Project, Tag, Request

class SearchForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['tag']

class CreateProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'status', 'contributors', 'tags']

class CreateRequestForm(ModelForm):
    class Meta:
        model = Request
        fields = ['note']

class CreateTagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['tag']

projects/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db import connection

from users.models import Project, Tag, Request, RequestStatus
from .forms import CreateProjectForm, SearchForm, CreateRequestForm, CreateTagForm

# Create your views here.
def home_view(request):
    #Determine the base and projects
    if not request.user.is_authenticated:
        base = "users/base.html"
        #One raw sql query for final_project requirements
        projects = Project.objects.raw("SELECT * FROM users_project")
    else:
        user = request.user
        base = "projects/base.html"
        projects = Project.objects.exclude(contributors = request.user).exclude(manager = request.user).all()

    #Modify the projects to be returned if it's a post request
    if request.method == "POST":
        #Create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        #Check whether it's valid
        if form.is_valid():
            #Since it's valid, filter the projects by their tag
            tag = form.cleaned_data['tag']
            tag = Tag.objects.get(tag = tag)
            projects = Project.objects.filter(tags = tag.id)

    #Render the page with the appropriate context
    context = {
        "projects": projects,
        "base": base,
        "form": SearchForm()
    }
    return render(request, "projects/home.html", context)

def create_tag_view(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    if request.method == 'POST':
        #Create a form instance and populate it with data from the request:
        form = CreateTagForm(request.POST)
        #Check whether it's valid
        if form.is_valid():
            #Get the form data
            tag = form.cleaned_data['tag']

            #Create the tag
            tag = Tag.objects.create(tag = tag)

            #Redirect to previous page
            next = request.POST.get('next', '/')
            return redirect(next)
    #Since it's a get request, render the page with the form
    else:
        context = {
            "form": CreateTagForm(),
            "next": request.META['HTTP_REFERER']
        }
        return render(request, "projects/create_tag.html", context)

def create_view(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    if request.method == 'POST':
        #Create a form instance and populate it with data from the request:
        form = CreateProjectForm(request.POST)
        #Check whether it's valid
        if form.is_valid():
            #Get the form data
            name = form.cleaned_data['name']
            manager = request.user
            status = form.cleaned_data['status']
            contributors = form.cleaned_data['contributors']
            description = form.cleaned_data['description']

            #Create the project
            project = Project.objects.create(name = name, manager = manager, status = status, description = description)
            for contributor in contributors:
                project.contributors.add(contributor)

            #Redirect to manage
            return redirect('projects:manage')
    else:
        form = CreateProjectForm()

    return render(request, "projects/create.html", {'form': form})

def manage_view(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    context = {
        "managed_projects": request.user.manager.all(),
        "contributed_projects": request.user.contributor.all()
    }
    return render(request, "projects/manage.html", context)

def manage_project_view(request, project_id):
    #Get the project in question
    project = Project.objects.get(pk = project_id)

    #Set the appropriate base
    if not request.user.is_authenticated:
        base = "users/base.html"
    else:
        base ="projects/base.html"
    #Check whether the user is the contributor, the manager, or viewer
    #Return the appropriate html page
    if project.manager == request.user:
        #Pre-fill the form with all the appropriate fields
        data = {'name': project.name,
                'description': project.description,
                'status': project.status,
                'contributors': project.contributors.all(),
                'tags': project.tags.all()}
        form = CreateProjectForm(initial=data)

        #Create the context
        context = {'form': form,
                   'project': project,
                   'base': base}
        return render(request, "projects/project_manager.html", context)

    elif project.contributors.filter(id = request.user.id).count() != 0:
        role = "Contributor"
    else:
        role = "Viewer"
    #Establish the context
    context = {
        "project": project,
        "role": role,
        'base': base
    }
    return render(request, "projects/project.html", context)

def modify_project_view(request, project_id):
    if request.method == 'POST':
        #Get the current project
        project = Project.objects.get(pk = project_id)

        #Create a form instance and populate it with data from the request:
        form = CreateProjectForm(request.POST)
        #Check whether it's valid
        if form.is_valid():
            #Edit the project with the form data
            project.name = form.cleaned_data['name']
            project.status = form.cleaned_data['status']
            project.description = form.cleaned_data['description']

            #Create a separate loop for contributors and tags
            project.contributors.clear()
            for contributor in form.cleaned_data['contributors']:
                project.contributors.add(contributor)

            project.tags.clear()
            for tag in form.cleaned_data['tags']:
                project.tags.add(tag)

            project.save()

    #Redirect to manage
    return redirect('projects:manage')

def request_view(request, project_id):
    if request.method == "POST":
        #Get the information from the form
        form = CreateRequestForm(request.POST)
        #Check whether it's valid
        if form.is_valid():
            note = form.cleaned_data['note']

            #Create the new Request
            #Second required SQL code
            cursor = connection.cursor()
            cursor.execute("INSERT INTO users_request (sender_id, project_id, status_id, note) VALUES (%s, %s, %s, %s)", [request.user.id, project_id, 3, note])

        return redirect('projects:myrequests')
    else:
        #If the user isn't signed in, redirect them to the signin page
        if not request.user.is_authenticated:
            return render(request, "users/login.html", {"next":request.path})
        #If the user is signed in but is already a member of the team, redirect them to the project page
        project = Project.objects.get(pk = project_id)
        if project.manager == request.user or request.user.contributor.filter(id=project.id).exists():
            return redirect(reverse('projects:manage_project', args=(project_id,)))
        form = CreateRequestForm()
        context = {
            "project": project,
            "form": form
        }
        return render(request, "projects/request.html", context)

def myrequests_view(request):
    user = request.user

    context = {
        "sent_requests": Request.objects.filter(sender=request.user),
        "received_requests": Request.objects.filter(project__manager = user)
    }
    return render(request, "projects/myrequests.html", context)

#If the link to approve a request is clicked
def approve_view(request, request_id):
    received_request = Request.objects.get(pk = request_id)
    if received_request.project.manager == request.user:
        #Change the status of the user
        received_request.status = RequestStatus.objects.get(status = 'Approved')
        received_request.save()

        #Add the sender to the contributors list
        received_request.project.contributors.add(received_request.sender)

        return redirect('projects:myrequests')
    else:
        raise Http401("You need to be a manager to modify the status of a request")

#If the link to deny a request is clicked
def deny_view(request, request_id):
    received_request = Request.objects.get(pk = request_id)
    if received_request.project.manager == request.user:
        received_request.status = RequestStatus.objects.get(status = 'Denied')
        received_request.save()
        return redirect('projects:myrequests')
    else:
        raise Http401("You need to be a manager to modify the status of a request")

def request_modification_view(request, request_id, modification_id):
    #Move into a try statement
    received_request = Request.objects.get(pk = request_id)

    #If they are a manager, modify the request accordingly
    if received_request.project.manager == request.user:
        received_request.status = modification_id
        #received_request.note = note
        received_request.save()
        return redirect('projects:myrequests')
    else:
        raise Http401("You need to be a manager to modify the status of a request")

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
      {% block head %}
      {% endblock %}
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <!-- CSS only -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

      <!-- JS, Popper.js, and jQuery -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title>ProDium </title>
    </head>
    <body class = "m-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:home' %}">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:create' %}">Create<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:create_tag' %}">Create Tag</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:manage' %}">MyProjects<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projects:myrequests' %}">MyRequests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
        <h1>{% block heading %}{% endblock %}</h1>

        {% block body %}
        {% endblock %}
    </body>
</html>

projects/templates/projects/create.html
{% extends "projects/base.html" %}

{% block body %}
  <h1>Create</h1>
  <form action="{% url 'projects:create' %}" method="post" onsubmit="return formConfirmation()">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{field.label}} <br>
        {{field}}<br>
        <small class="text=muted">{{field.help_text}}</small>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.label == "Tags" %}
          <a href="{% url 'projects:create_tag'%}" class = "btn btn-success">Create Tag</a>
        {% endif %}
      </p>
    {% endfor %}
    <input type="submit" class = "btn btn-info" value="Submit"></input>
  </form>
  <button class="btn btn-danger" onclick="history.back()">Cancel</button>

  <script>
    function formConfirmation() {
      var conf = confirm('Please confirm the following information. Projects cannot be deleted once made.');
      return conf;
    };
  </script>
{% endblock %}

projects/templates/projects/create_tag.html
{% extends "projects/base.html" %}

{% block body %}
  <h1>Create</h1>
  <form action="{% url 'projects:create_tag' %}" method="post" onsubmit="return formConfirmation()">
    {% csrf_token %}
    {{form}}
    <input type='hidden' name = "next" value = "{{next}}">
    <input type="submit" class = "btn btn-info" value="Submit"></input>
  </form>
  <button class="btn btn-danger" onclick="history.back()">Cancel</button>

  <script>
    function formConfirmation() {
      var conf = confirm('Please confirm the following information. Tags cannot be deleted once made.');
      return conf;
    };
  </script>
{% endblock %}

projects/templates/projects/home.html
{% extends base %}
{% block head %}
{% load static %}
<script src = "{% static 'projects/js/hide_content.js' %}"></script>
<script src = "{% static 'projects/css/hide_content.css' %}"></script>
{% endblock %}

{% block body %}
  <h1>Home</h1>
  <form action="{% url 'projects:home' %}" method="post">
    {% csrf_token %}
    {{form}}
  </form>
  {% for project in projects %}
    <div class="{{project.status.cardClass.cardClass}} project">
      <div class="card-body">
          {{project.name}}<br>
          Tags:
            {% for tag in project.tags.all %}
              #{{tag}}
            {% endfor %}
        <button class="btn btn-primary float-right" data-toggle="collapse" data-target="#{{project.id}}_collapse" aria-expanded="true" aria-controls="{{project.id}}_collapse">
            More
        </button>
        <button class="float-right btn btn-secondary hide">Hide</button>
      </div>
    </div>
    <div id="{{project.id}}_collapse" class="collapse hide" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card card-body">
        <h6 class="card-subtitle mb-2 text-muted">{{project.status}}</h6>
        Manager: {{project.manager}} <br>
        Description: {{project.description}} <br>
        <a href="{% url 'projects:request' project.id %}" class="float-right btn btn-primary">Get Involved</a>
      </div>
    </div>
  {% endfor %}
  <style>
      @keyframes hide {
          0% {
              opacity: 1;
              height: 100%;
              line-height: 100%;
          }
          75% {
              opacity: 0;
              height: 100%;
              line-height: 100%;
          }
          85% {
            opacity: 0;
            height: 0px;
            line-height: 0px;
          }
          100% {
            opacity: 0;
            height: 0px;
            line-height: 0px;
          }
      }

      .project {
          animation-name: hide;
          animation-duration: 1s;
          animation-fill-mode: forwards;
          animation-play-state: paused;
      }
  </style>
{% endblock %}

projects/templates/projects/manage.html
{% extends "projects/base.html" %}

{% block body %}
  <h1>MyProjects</h1>
  <h2>Managing</h2>
  {% for project in managed_projects %}
  <div class="{{project.status.cardClass.cardClass}}">
    <div class="card-body">
      <h5 class = "card-title"> {{project.name}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{project.status}}</h6>
      Description: {{project.description}} <br>
      Tags: {% for tag in project.tags.all %}#{{tag}} {% endfor %}
      <a href="{% url 'projects:manage_project' project.id%}" class="float-right btn btn-primary">Edit</a>
    </div>
  </div>
  {% endfor %}
  <h2>Contributing</h2>
  {% for project in contributed_projects %}
  <div class="{{project.status.cardClass.cardClass}}">
    <div class="card-body">
      <h5 class = "card-title"> {{project.name}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{project.status}}</h6>
      Description: {{project.description}} <br>
      Tags: {% for tag in project.tags.all %}#{{tag}} {% endfor %}
      <a href="{% url 'projects:manage_project' project.id%}" class="float-right btn btn-primary">More</a>
    </div>
  </div>
  {% endfor %}
{% endblock %}

projects/templates/projects/myrequests.html
{% extends "projects/base.html" %}
{% block body %}
  <h1>My Requests</h1>
  <h2> Received Requests </h2>
    {% for request in received_requests %}
    <div class="{{request.status.cardClass.cardClass}}">
      <div class="card-body">
          {{request}}<br>
          Notes: {{request.note}}
          {% if request.status.status == "Pending" %}
            <a class="float-right btn btn-primary modify"  href="{% url 'projects:deny' request.id %}">Deny</a>
            <a class="float-right btn btn-primary modify"  href="{% url 'projects:approve' request.id %}">Approve</a>
          {% endif %}
      </div>
    </div>
    {% empty %}
    No Received Requests
    {% endfor %}
  <h2> Sent Requests </h2>
    {% for request in sent_requests %}
    <div class="{{request.status.cardClass.cardClass}}">
      <div class="card-body">
          {{request}}<br>
          Notes:
            {{request.note}}
      </div>
    </div>
    {% empty %}
      No sent requests
    {% endfor %}
{% endblock %}

projects/templates/projects/project.html
{% extends base %}
{% block body %}

{% if message %}
  <div> {{message}} </div>
{% endif %}

<div class="{{project.status.cardClass.cardClass}}">
  <div class="card-body">
      <h5 class = "card-title"> {{project.name}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{project.status}}</h6>
      Manager: {{project.manager}} <br>
      Description: {{project.description}} <br>
      Tags: {% for tag in project.tags.all %}{{tag}}{% endfor %}<br>
      Role: {{role}}
      {% if role == "Viewer" %}
        <a href="{% url 'projects:request' project.id %}" class="float-right btn btn-primary">Get Involved</a>
      {% endif %}
  </div>
</div>
{% endblock %}

projects/templates/projects/project_manager.html
{% extends base %}
{% block body %}
<form action = "{% url 'projects:modify_project' project.id %}" method="post">
  {% csrf_token %}
  {%for field in form %}
    <p>
      {{ field.label_tag}}<br>
      {{field}}
      {% if field.help_text %}
        <small style="color: grey"> {{field.help_text}} </small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
      {% if field.label == "Tags" %}
        <a href="{% url 'projects:create_tag'%}" class = "btn btn-success">Create Tag</a>
      {% endif %}
    </p>
  {% endfor %}
  <input type="Submit" class = "btn btn-info" value = "Submit"></input>
</form>
<button class="btn btn-danger" onclick="history.back()">Cancel</button>
{% endblock %}

projects/templates/projects/request.html
{% extends "projects/base.html" %}

{% block body %}
<form action="{% url 'projects:request' project.id %}" method="post">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Send Request"></input>
</form>
{% endblock %}